[service]
golangci-lint-version =  "1.51.2"

[linters]
disable-all = true

enable = [
    # "asasalint", workaround
    "asciicheck",
    "bidichk",
    "bodyclose",
    "containedctx",
    "contextcheck",
    "cyclop",
    # "deadcode", deprecated
    "decorder",
    # "depguard",
    "dogsled",
    "dupl",
    "dupword",
    "durationcheck",
    "errcheck",
    "errchkjson",
    "errname",
    "errorlint",
    "execinquery",
    "exhaustive",
    # "exhaustivestruct", deprecated
    # "exhaustruct", quite difficult to enable for partial struct init
    "exportloopref",
    "forbidigo",
    "forcetypeassert",
    # "funlen", the complexity is covering most of issues
    "gci",
    "gochecknoglobals",
    "gochecknoinits",
    "gocognit",
    "goconst",
    #"gocritic",
    "gocyclo",
    # "godot", the dot is not always easy to add (multiline for ex)
    # "godox", workaround
    "goerr113",
    "gofmt",
    "gofumpt",
    "goheader",
    "goimports",
    # "golint", deprecated
    "gomnd",
    "gomoddirectives",
    "gomodguard",
    "goprintffuncname",
    "gosec",
    "gosimple",
    "govet",
    "grouper",
    # "ifshort", deprecated
    "importas",
    "ineffassign",
    # "interfacebloat", workaround
    # "interfacer" [deprecated]: Linter that suggests narrower interface types [fast: false, auto-fix: false]
    # "ireturn", workaround
    "lll",
    "loggercheck",
    "maintidx",
    "makezero",
    # "maligned", deprecated
    "misspell",
    "nakedret",
    "nestif",
    "nilerr",
    "nilnil",
    "nlreturn",
    "noctx",
    "nolintlint",
    # "nonamedreturns", workaround
    # "nosnakecase", deprecated
    "nosprintfhostport",
    "paralleltest",
    "prealloc",
    "predeclared",
    "promlinter",
    "reassign",
    "revive",
    "rowserrcheck",
    # "scopelint", deprecated
    "sqlclosecheck",
    "staticcheck",
    # "structcheck", deprecated
    # "stylecheck",
    # "tagliatelle",
    "tenv",
    "testableexamples",
    # "testpackage",
    "thelper",
    "tparallel",
    "typecheck",
    "unconvert",
    "unparam",
    "unused",
    "usestdlibvars",
    # "varcheck", deprecated
    # "varnamelen", workaround
    "wastedassign",
    "whitespace",
    # "wrapcheck", workaround
    # "wsl", workaround
]

[linters-settings.errcheck]
check-type-assertions = true
check-blank = true

[linters-settings.govet]
check-shadowing = true

[linters-settings.revive]
min-confidence = 0.0

[linters-settings.prealloc]
simple = false
range-loops = true
for-loops = true

[linters-settings.gocritic]
enabled-tags = [
    "diagnostic",
    "experimental",
    "opinionated",
    "performance",
    "style",
]
disabled-checks = [
    "whyNoLint",
]

[linters-settings.errorlint]
errorf = true

[linters-settings.nolintlint]
require-explanation = true
require-specific = true

[linters-settings.gofumpt]
extra-rules = true

[[issues.exclude-rules]]
path = '(.+)_test\.go'
linters = ["funlen", "goconst", "interfacer", "dupl", "lll", "goerr113", "varnamelen", "errcheck", "gocritic", "cyclop", "wrapcheck"]

[[issues.exclude-rules]]
path = 'sqlc\.go'
linters = ["wrapcheck"]

[[issues.exclude-rules]]
source = "^//go:generate "
linters = ["lll"]

[run]
# which dirs to skip: issues from them won't be reported;
# can use regexp here: generated.*, regexp is applied on full path;
# default value is empty list, but default dirs are skipped independently
# from this option's value (see skip-dirs-use-default).
# "/" will be replaced by current OS file path separator to properly work
# on Windows.
skip-dirs = [
    "third_party.*",
    "api.*",
    "tools.*",
    "pb.*",
]
