repos:
  - repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
      - id: black
        exclude:
          "(?x)(\n  ^third_party/|\n  ^tools/|\n  ^api/|\n  ^internal/app/pb/\n
          \ )\n"
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.59.1
    hooks:
      - id: golangci-lint
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: validate-toml
      - id: no-go-testing
      - id: golangci-lint
      - id: go-mod-tidy
