// Code generated by "stringer -type=DownloadType"; DO NOT EDIT.

package dto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DailyClose-0]
	_ = x[ThreePrimary-1]
	_ = x[Concentration-2]
	_ = x[StockList-3]
}

const _DownloadType_name = "DailyCloseThreePrimaryConcentrationStockList"

var _DownloadType_index = [...]uint8{0, 10, 22, 35, 44}

func (i DownloadType) String() string {
	if i < 0 || i >= DownloadType(len(_DownloadType_index)-1) {
		return "DownloadType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DownloadType_name[_DownloadType_index[i]:_DownloadType_index[i+1]]
}
