# Server configurations
server:
  name: "stock-crawler"
  host: "0.0.0.0"
  port: 8086
  maxGoroutine: 20000
  dnsLatency: 200

redis:
  sentinelAddrs: ["redis-sentinel-1:26379", "redis-sentinel-2:26380", "redis-sentinel-3:26381"]
  master: "redis-master"

kafka:
  controller: "kafka-1:9092"

crawler:
  fetchWorkers: 30
  rateLimit: 1000
