# Server configurations
server:
  name: "stock-crawler"
  host: "0.0.0.0"
  port: 8086

redis:
  sentinelAddrs: ["redis-sentinel-1:26379", "redis-sentinel-2:26380", "redis-sentinel-3:26381"]
  master: "redis-master"

# Logging
log:
  level: "DEBUG"

# WorkerPool
workerpool:
  maxPoolSize: 10
  maxQueueSize: 20

kafka:
  port: 9092
  host: "kafka-1"
