# Server configurations
server:
  name: "stock-crawler"
  host: "0.0.0.0"
  port: 8086

redis:
  port: 6379
  host: "redis-cache"

# Logging
log:
  level: "DEBUG"

# WorkerPool
workerpool:
  maxPoolSize: 40
  maxQueueSize: 80

kafka:
  port: 9092
  host: "localhost"
