# Server configurations
server:
  name: "stock-crawler"
  host: "0.0.0.0"
  version: "v2.0.2"
  port: 8086
  maxGoroutine: 20000
  dnsLatency: 200

redis:
  sentinelAddrs:
    [
      "redis-sentinel-1:26379",
      "redis-sentinel-2:26380",
      "redis-sentinel-3:26381"
    ]
  master: "redis-master"
  port: 6379

kafka:
  controller: "kafka-1:9092"
  brokers: [ "kafka-1:9092", "kafka-2:9092", "kafka-3:9092" ]
  topics: [ "download-v1" ]
  groupId: "jarvis"

crawler:
  fetchWorkers: 10
  rateLimit: 3000
