# Server configurations
server:
  name: "stock-crawler"
  host: "0.0.0.0"
  port: 8086

redis:
  ports: [":26379", ":26380", ":26381"]
  master: "redis-master"

# Logging
log:
  level: "DEBUG"

# WorkerPool
workerpool:
  maxPoolSize: 40
  maxQueueSize: 80

kafka:
  port: 9092
  host: "localhost"
