# Server configurations
server:
  name: "stock-crawler"
  host: "0.0.0.0"
  port: 8086
  maxGoroutine: 20000
  dnsLatency: 200

redis:
  sentinelAddrs: [ "redis-sentinel-headless:26379" ]
  master: "redis-sentinel"
  port: 6379

kafka:
  controller: "kafka:9092"
  brokers: [ "kafka-headless:9092" ]
  topics: [ "download-v1" ]
  groupId: "jarvis"

crawler:
  fetchWorkers: 40
  rateLimit: 500
